
# Overview of Statistical Learning

This chapter is very conceptual and there isn't any code to mess with.

## Exercises

1. ISL 2.1: For each part below, indicate whether we would generally expect the performance of a flexible statistical learning method to be better or worse than an inflexible method. Justify your answer.
    a) The sample size n is extremely large, and the number of predictors p is small.
    b) The number of predictors p is extremely large, and the number of observations n is small.
    c) Relationship between the predictors and response is highly non-linear.
    d) The variance of the error terms, i.e. $\sigma^{2}=Var\left(\epsilon\right)$, is extremely high.

2. ISL 2.2: Explain whether each scenario is a classification or regression problem, and indicate whether we are most interested in inference or prediction. Finally, provide $n$ and $p$.
    a) We collect a set of data on the top 500 firms in the US. For each firm we record profit, number of employees, industry and the CEO salary. We are interested in understanding which factors affect CEO salary.
    b) We are considering launching a new product and wish to know whether it will be a `success` or `failure`. We collect data on 20 similar products that were previously launched. For each product we have recored whether it was a success or failure, price charged for the product, marketing budget, competition price, and ten other variables.
    c) We are interested in predicting the % change in the US dollar in relation to the weekly changes in the world stock markets. Hence we collect weekly data for all of 2012. For each week we record the % change in the dollar, the % change in the US market, the % change in the British market, and the % change in the German market.

3. ISL 2.3: We new revisit the bias-variance decomposition.
    a) Provide a sketch of typical (squared) bias, variance, training error, test error, and Bayes (or irreducible) error curves, on a single plot, as we go from less flexible statistical learning methods towards more flexible approaches. The x-axis should represent the amount of flexibility in the method, and the y-axis should represent the values for each curve. There should be five curves. Make sure to label each one.
    b) Explain why each of the five curves has the shape displayed in part (a).
